<a href="https://colab.research.google.com/github/Hiwotyirga/-a-functionality-that-represents-the-relationships-between-GSEs-and-GSMs/blob/main/IcogTask.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [116]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression

from sklearn.model_selection import train_test_split
import torch
import torch.nn as nn
import torch.optim as optim
from sklearn.preprocessing import StandardScaler
from torch.utils.data import TensorDataset, DataLoader


In [65]:
iris=load_iris()

In [66]:
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [67]:
iris['data']

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [68]:
iris['target']


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [69]:
iris['feature_names']


['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [70]:
iris_df = pd.DataFrame(data=iris['data'], columns=iris['feature_names'])
iris_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [71]:
iris_df['label'] = iris['target']
iris_df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   label  
0      0  
1      0  
2      0  
3      0  
4      0

In [111]:
iris_df['label'].value_counts()

label
0    50
1    50
2    50
Name: count, dtype: int64

In [72]:
np.random.seed(4953)

In [73]:
x = iris_df.drop(columns='label')
y = iris_df['label']

In [74]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3)

In [75]:
x_train

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
94                 5.6               2.7                4.2               1.3
60                 5.0               2.0                3.5               1.0
139                6.9               3.1                5.4               2.1
87                 6.3               2.3                4.4               1.3
145                6.7               3.0                5.2               2.3
..                 ...               ...                ...               ...
110                6.5               3.2                5.1               2.0
130                7.4               2.8                6.1               1.9
27                 5.2               3.5                1.5               0.2
98                 5.1               2.5                3.0               1.1
38                 4.4               3.0                1.3               0.2

[105 rows x 4 columns]

In [104]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(x_train)
X_test_scaled = scaler.transform(x_test)

In [112]:
c_values = [0.01, 0.1, 1, 10]


In [123]:
results = []

for c in c_values:
    # Initialize model with current C
    model = LogisticRegression(C=c, solver='liblinear', multi_class='ovr', random_state=42)

    # Train
    model.fit(X_train_scaled, y_train)

    # Predict
    y_pred = model.predict(X_test_scaled)

    # Calculate metrics
    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred, average='macro')
    recall = recall_score(y_test, y_pred, average='macro')
    f1 = f1_score(y_test, y_pred, average='macro')

    # Store results
    results.append({
        'C': c,
        'Accuracy': accuracy,
        'Precision': precision,
        'Recall': recall,
        'F1 Score': f1
    })

# Convert results to DataFrame
results_df = pd.DataFrame(results)
print(results_df)

       C  Accuracy  Precision    Recall  F1 Score
0   0.01  0.822222   0.835017  0.809117  0.812121
1   0.10  0.822222   0.823362  0.823362  0.823362
2   1.00  0.866667   0.878151  0.881766  0.870833
3  10.00  0.933333   0.937500  0.944444  0.935214


/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:1256: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:1256: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:1256: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:1256: FutureWarning: 'multi_class' was depre

In [137]:
dt = LogisticRegression(class_weight="balanced")

In [138]:
dt.fit(X_train_scaled, y_train)

LogisticRegression(class_weight='balanced')

In [139]:
dt.predict(X_test_scaled)

array([1, 0, 0, 0, 1, 1, 2, 1, 1, 2, 1, 0, 2, 2, 2, 2, 0, 0, 2, 1, 1, 2,
       1, 1, 2, 0, 2, 0, 0, 2, 0, 1, 1, 0, 0, 1, 2, 0, 2, 1, 1, 0, 2, 2,
       1])

In [140]:
pred = dt.predict(X_test_scaled)

In [141]:
pred

array([1, 0, 0, 0, 1, 1, 2, 1, 1, 2, 1, 0, 2, 2, 2, 2, 0, 0, 2, 1, 1, 2,
       1, 1, 2, 0, 2, 0, 0, 2, 0, 1, 1, 0, 0, 1, 2, 0, 2, 1, 1, 0, 2, 2,
       1])

In [142]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

pred = dt.predict(X_test_scaled)


acc = accuracy_score(y_test, pred)

precision = precision_score(y_test, pred, average='macro')
recall = recall_score(y_test, pred, average='macro')
f1 = f1_score(y_test, pred, average='macro')

print("Accuracy:", acc)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)


Accuracy: 0.9333333333333333
Precision: 0.9375
Recall: 0.9444444444444445
F1 Score: 0.9352142110762801


In [130]:
train_data = TensorDataset(
    torch.FloatTensor(X_train_scaled),
    torch.LongTensor(y_train.values)
)

test_data = TensorDataset(
    torch.FloatTensor(X_test_scaled),
    torch.LongTensor(y_test.values)
)


In [131]:
train_loader = DataLoader(train_data, batch_size=32, shuffle=True)
test_loader = DataLoader(test_data, batch_size=32)


In [132]:
class SimpleNN(nn.Module):
    def __init__(self, input_dim, hidden_dim, output_dim):
        super(SimpleNN, self).__init__()
        self.net = nn.Sequential(
            nn.Linear(input_dim, hidden_dim),
            nn.ReLU(),
            nn.Linear(hidden_dim, output_dim))

    def forward(self, x):
        return self.net(x)


In [133]:
model = SimpleNN(input_dim=X_train_scaled.shape[1], hidden_dim=16, output_dim=num_classes)


In [134]:
num_classes = len(np.unique(y_train))
print("Number of classes:", num_classes)


Number of classes: 3


In [135]:
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.01)

num_epochs = 200
for epoch in range(num_epochs):
    model.train()
    for batch_x, batch_y in train_loader:
        outputs = model(batch_x)
        loss = criterion(outputs, batch_y)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

    if (epoch+1) % 10 == 0:
        print(f"Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item():.4f}")


Epoch [10/200], Loss: 0.1352
Epoch [20/200], Loss: 0.2826
Epoch [30/200], Loss: 0.1559
Epoch [40/200], Loss: 0.0880
Epoch [50/200], Loss: 0.0220
Epoch [60/200], Loss: 0.1996
Epoch [70/200], Loss: 0.1343
Epoch [80/200], Loss: 0.0071
Epoch [90/200], Loss: 0.0354
Epoch [100/200], Loss: 0.0079
Epoch [110/200], Loss: 0.0360
Epoch [120/200], Loss: 0.0017
Epoch [130/200], Loss: 0.0039
Epoch [140/200], Loss: 0.0212
Epoch [150/200], Loss: 0.1170
Epoch [160/200], Loss: 0.0884
Epoch [170/200], Loss: 0.0195
Epoch [180/200], Loss: 0.0006
Epoch [190/200], Loss: 0.0623
Epoch [200/200], Loss: 0.0664


In [136]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

model.eval()
all_preds = []
all_labels = []

with torch.no_grad():
    for inputs, labels in test_loader:
        outputs = model(inputs)
        _, preds = torch.max(outputs, 1)
        all_preds.extend(preds.cpu().numpy())
        all_labels.extend(labels.cpu().numpy())

print("\nNeural Network Performance:")
print(f"Accuracy: {accuracy_score(all_labels, all_preds):.4f}")
print(f"Precision: {precision_score(all_labels, all_preds, average='macro'):.4f}")
print(f"Recall: {recall_score(all_labels, all_preds, average='macro'):.4f}")
print(f"F1 Score: {f1_score(all_labels, all_preds, average='macro'):.4f}")
print("Confusion Matrix:")
print(confusion_matrix(all_labels, all_preds))


Neural Network Performance:
Accuracy: 0.9333
Precision: 0.9375
Recall: 0.9444
F1 Score: 0.9352
Confusion Matrix:
[[14  0  0]
 [ 0 13  0]
 [ 0  3 15]]
